CC =gcc
CFLAGS = -std=gnu99 -pedantic -Wall

helloworld: helloworld.o talk.o
	$(CC) -o $@ helloworld.o talk.o

.PHONY: clean depend
clean:
	rm -f  *.o *.h~ *.c~ helloworld
depend:
	makedepend   talk.c helloworld.c
# DO NOT DELETE

#talk.o: talk.h
#helloworld.o: talk.h
